[package]
name = "launch-blocker"
version = "0.1.0"
authors = ["qbx2 <sunyeop97@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[profile.release]
lto = true
